### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by Kenshokram** [JeanxPereira/CMI-Sprites#2]
Hi! I was surprised at the complete lack of a rip of the sprites from CMI on the internet, have you abandoned this project?

Also, Guybrush is marked as ripped but I could not find any files for him here.

**Comment by JeanxPereira** [comment]
Hi! After a long time without updates I will continue the project, due to lack of time due to studies and work I ended up not paying attention to my personal projects, but now I'm back

**Comment by Kenshokram** [comment]
That's amazing news! :) Thank you for the endeavor. I was thinking of trying to set up a sort of "Guybrush v-tuber" that just animates through the sprites from voice recognition, for fun (I'm not a streamer) and I wasn't able to find anything other than walk cycles on the internet lol

**Comment by arcanetrivia** [comment]
Oh, yay! I was worried this had been abandoned, too.
